services:
    frontend:
        container_name: frontend
        image: frontend:dev
        build:
            dockerfile: react.dockerfile
        ports:
            - "${REACT_PORT}:${REACT_PORT}"
        depends_on:
            backend:
                condition: service_started

    backend:
        container_name: backend
        image: ceoshikhar/arthveda-backend:dev
        build:
            dockerfile: go.dockerfile
        environment:
            APP_ENV: ${GO_APP_ENV}
            GO_PORT: ${GO_PORT}
            DB_HOST: ${POSTGRES_HOST}
            DB_PORT: ${POSTGRES_PORT}
            DB_NAME: ${POSTGRES_DB}
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            GO_JWT_SECRET: ${GO_JWT_SECRET}
            GO_LOG_LEVEL: ${GO_LOG_LEVEL}
            GO_LOG_FILE: ${GO_LOG_FILE}
        ports:
            - 1337:1337
        depends_on:
            database:
                condition: service_healthy
                restart: true

    database:
        container_name: database
        image: postgres:17.4
        environment:
            PGPORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
            - ~/docker_volumes/arthveda_postgresql_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
