networks:
    arthveda_network:
        name: arthveda_network

services:
    client:
        container_name: client
        build:
            dockerfile: client.dockerfile
        ports:
            - "${REACT_PORT}:${REACT_PORT}"
        networks:
            - arthveda_network
        depends_on:
            server:
                condition: service_started

    server:
        container_name: server
        image: ceoshikhar/arthveda-server:dev
        build:
            dockerfile: server.dockerfile
        environment:
            GO_APP_ENV: ${GO_APP_ENV}
            GO_PORT: ${GO_PORT}
            GO_JWT_SECRET: ${GO_JWT_SECRET}
            GO_LOG_LEVEL: ${GO_LOG_LEVEL}
            GO_LOG_FILE: ${GO_LOG_FILE}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${GO_PORT}:${GO_PORT}"
        networks:
            - arthveda_network
        depends_on:
            database:
                condition: service_healthy
                restart: true

    database:
        container_name: database
        image: postgres:17.4
        environment:
            PGPORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        networks:
            - arthveda_network
        volumes:
            - /var/lib/arthveda/postgresql/data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
