services:
    frontend:
        container_name: frontend
        image: frontend:1.0.0
        build:
            context: ./frontend
            dockerfile: react.dockerfile
        ports:
            - 1337:1337
        depends_on:
            - backend

    backend:
        container_name: backend
        image: backend:1.0.0
        build:
            context: ./backend
            dockerfile: go.dockerfile
        environment:
            APP_ENV: production
            FRONTEND_URL: http://localhost:1337
            DB_HOST: host.docker.internal
            DB_NAME: postgres
            DB_USER: postgres
            DB_PASSWORD: postgres
            LISTEN_PORT: :6969
            SESSION_KEY: super_secret_session_key_for_signing
        ports:
            - 6969:6969
        depends_on:
            - database

    database:
        container_name: database
        image: postgres:17.4
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - database_data:/var/lib/postgresql/data

volumes:
    database_data: {}
