services:
    nginx:
        image: nginx:1.27
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - 80:80
        depends_on:
            frontend:
                condition: service_started

    frontend:
        container_name: frontend
        image: frontend:1.0.0
        build:
            context: ./frontend
            dockerfile: react.dockerfile
        ports:
            - 1337:1337
        depends_on:
            backend:
                condition: service_started

    backend:
        container_name: backend
        image: backend:1.0.0
        build:
            context: ./backend
            dockerfile: go.dockerfile
        environment:
            APP_ENV: production
            DB_HOST: database
            DB_PORT: 5432
            DB_NAME: ${POSTGRES_DB}
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            LISTEN_PORT: :6969
            JWT_SECRET: ${JWT_SECRET}
        ports:
            - 6969:6969
        depends_on:
            database:
                condition: service_healthy
                restart: true

    database:
        container_name: database
        image: postgres:17.4
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - database_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 10s
            retries: 5
            timeout: 10s

volumes:
    database_data: {}
