include:
    - compose.yaml
services:
    nginx:
        container_name: nginx
        image: nginx:1.27
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - 80:80
        depends_on:
            frontend:
                condition: service_started
