name: "dev: build & deploy backend"

on:
    push:
        branches: ["dev"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: DockerHub login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Setup .env
              run: |
                  touch .env
                  echo "GO_PORT=1337" >> .env
                  echo "POSTGRES_PORT=42069" >> .env
                  cat .env

            - name: Build and push to DockerHub
              run: |
                  cat .env
                  docker compose build backend
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/arthveda-backend:dev

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Add VPS to known_hosts
              run: |
                  ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to VPS
              run: |
                  ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull backend && docker compose up backend -d && exit"
